// USUARIO LOGIN
export const START_USUARIO_LOGIN = 'START_USUARIO_LOGIN';
export const END_USUARIO_LOGIN = 'END_USUARIO_LOGIN';
export const UPDATE_USUARIO_LOGIN = 'UPDATE_USUARIO_LOGIN';
// USUARIO LOGOUT
export const START_USUARIO_LOGOUT = 'START_USUARIO_LOGOUT';
export const END_USUARIO_LOGOUT = 'END_USUARIO_LOGOUT';
export const UPDATE_USUARIO_LOGOUT = 'UPDATE_USUARIO_LOGOUT';
// SNACKBAR
export const UPDATE_SNACKBAR = 'UPDATE_SNACKBAR';
